# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissions', '0002_user_github_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('published', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('members', models.ManyToManyField(to='permissions.User')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(max_length=1024)),
                ('api_url', models.URLField(max_length=1024)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='repositories',
            field=models.ManyToManyField(to='projects.Repository'),
        ),
    ]
